// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dictybase/api/upload/file.proto

package upload

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FileUploadRequest) Validate() error {
	return nil
}
func (this *FileUploadResponse) Validate() error {
	return nil
}
