// @generated by protoc-gen-connect-es v1.3.0
// @generated from file dictybase/stock/stock.proto (package dictybase.stock, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExistingPlasmid, ExistingStrain, NewPlasmid, NewStrain, Plasmid, PlasmidCollection, PlasmidUpdate, StockId, StockIdList, StockParameters, Strain, StrainCollection, StrainList, StrainUpdate } from "./stock_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";
import { FileUploadRequest, FileUploadResponse } from "../api/upload/file_pb.js";

/**
 * The stock service specification
 *
 * @generated from service dictybase.stock.StockService
 */
export const StockService = {
  typeName: "dictybase.stock.StockService",
  methods: {
    /**
     * Retrieves strain by ID
     *
     * @generated from rpc dictybase.stock.StockService.GetStrain
     */
    getStrain: {
      name: "GetStrain",
      I: StockId,
      O: Strain,
      kind: MethodKind.Unary,
    },
    /**
     * Retrieves stock by ID
     *
     * @generated from rpc dictybase.stock.StockService.GetPlasmid
     */
    getPlasmid: {
      name: "GetPlasmid",
      I: StockId,
      O: Plasmid,
      kind: MethodKind.Unary,
    },
    /**
     * Create a new strain
     *
     * @generated from rpc dictybase.stock.StockService.CreateStrain
     */
    createStrain: {
      name: "CreateStrain",
      I: NewStrain,
      O: Strain,
      kind: MethodKind.Unary,
    },
    /**
     * Create a new plasmid
     *
     * @generated from rpc dictybase.stock.StockService.CreatePlasmid
     */
    createPlasmid: {
      name: "CreatePlasmid",
      I: NewPlasmid,
      O: Plasmid,
      kind: MethodKind.Unary,
    },
    /**
     * Update an existing strain
     *
     * @generated from rpc dictybase.stock.StockService.UpdateStrain
     */
    updateStrain: {
      name: "UpdateStrain",
      I: StrainUpdate,
      O: Strain,
      kind: MethodKind.Unary,
    },
    /**
     * Update an existing plasmid
     *
     * @generated from rpc dictybase.stock.StockService.UpdatePlasmid
     */
    updatePlasmid: {
      name: "UpdatePlasmid",
      I: PlasmidUpdate,
      O: Plasmid,
      kind: MethodKind.Unary,
    },
    /**
     * Remove an existing stock
     *
     * @generated from rpc dictybase.stock.StockService.RemoveStock
     */
    removeStock: {
      name: "RemoveStock",
      I: StockId,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * List strains using pagination, ten entries are retrieved by default
     *
     * @generated from rpc dictybase.stock.StockService.ListStrains
     */
    listStrains: {
      name: "ListStrains",
      I: StockParameters,
      O: StrainCollection,
      kind: MethodKind.Unary,
    },
    /**
     * List strains using strain id without any pagination
     *
     * @generated from rpc dictybase.stock.StockService.ListStrainsByIds
     */
    listStrainsByIds: {
      name: "ListStrainsByIds",
      I: StockIdList,
      O: StrainList,
      kind: MethodKind.Unary,
    },
    /**
     * List plasmids using pagination, ten entries are retrieved by default
     *
     * @generated from rpc dictybase.stock.StockService.ListPlasmids
     */
    listPlasmids: {
      name: "ListPlasmids",
      I: StockParameters,
      O: PlasmidCollection,
      kind: MethodKind.Unary,
    },
    /**
     * Load existing strain
     *
     * @generated from rpc dictybase.stock.StockService.LoadStrain
     */
    loadStrain: {
      name: "LoadStrain",
      I: ExistingStrain,
      O: Strain,
      kind: MethodKind.Unary,
    },
    /**
     * Load existing plasmid
     *
     * @generated from rpc dictybase.stock.StockService.LoadPlasmid
     */
    loadPlasmid: {
      name: "LoadPlasmid",
      I: ExistingPlasmid,
      O: Plasmid,
      kind: MethodKind.Unary,
    },
    /**
     * Upload obojson formatted file through client side streaming
     *
     * @generated from rpc dictybase.stock.StockService.OboJSONFileUpload
     */
    oboJSONFileUpload: {
      name: "OboJSONFileUpload",
      I: FileUploadRequest,
      O: FileUploadResponse,
      kind: MethodKind.ClientStreaming,
    },
  }
};

