// @generated by protoc-gen-es v1.6.0
// @generated from file dictybase/api/jsonapi/payload.proto (package dictybase.api.jsonapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * A [resource identifier object](http://jsonapi.org/format/#document-resource-identifier-objects).
 *
 * @generated from message dictybase.api.jsonapi.Data
 */
export declare class Data extends Message<Data> {
  /**
   * The resource name.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Unique id.
   *
   * @generated from field: int64 id = 2;
   */
  id: bigint;

  constructor(data?: PartialMessage<Data>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "dictybase.api.jsonapi.Data";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Data;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Data;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Data;

  static equals(a: Data | PlainMessage<Data> | undefined, b: Data | PlainMessage<Data> | undefined): boolean;
}

/**
 * Definition for resource identifier collection objects.
 *
 * @generated from message dictybase.api.jsonapi.DataCollection
 */
export declare class DataCollection extends Message<DataCollection> {
  /**
   * @generated from field: int64 id = 2;
   */
  id: bigint;

  /**
   * @generated from field: repeated dictybase.api.jsonapi.Data data = 1;
   */
  data: Data[];

  constructor(data?: PartialMessage<DataCollection>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "dictybase.api.jsonapi.DataCollection";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DataCollection;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DataCollection;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DataCollection;

  static equals(a: DataCollection | PlainMessage<DataCollection> | undefined, b: DataCollection | PlainMessage<DataCollection> | undefined): boolean;
}

/**
 * A container for http links.
 *
 * @generated from message dictybase.api.jsonapi.Links
 */
export declare class Links extends Message<Links> {
  /**
   * A http link. It points to the resource itself.
   *
   * @generated from field: string self = 1;
   */
  self: string;

  /**
   * A http link. It points to a related resource.
   *
   * @generated from field: string related = 2;
   */
  related: string;

  constructor(data?: PartialMessage<Links>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "dictybase.api.jsonapi.Links";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Links;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Links;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Links;

  static equals(a: Links | PlainMessage<Links> | undefined, b: Links | PlainMessage<Links> | undefined): boolean;
}

/**
 * A container for pagination links.
 *
 * @generated from message dictybase.api.jsonapi.PaginationLinks
 */
export declare class PaginationLinks extends Message<PaginationLinks> {
  /**
   * A http link to the resource itself.
   *
   * @generated from field: string self = 1;
   */
  self: string;

  /**
   * A http link to the next page of data.
   *
   * @generated from field: string next = 2;
   */
  next: string;

  /**
   * A http link to the previous page of data.
   *
   * @generated from field: string prev = 3;
   */
  prev: string;

  /**
   * A http link to the last page of data.
   *
   * @generated from field: string last = 4;
   */
  last: string;

  /**
   * A http link to the first page of data.
   *
   * @generated from field: string first = 5;
   */
  first: string;

  constructor(data?: PartialMessage<PaginationLinks>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "dictybase.api.jsonapi.PaginationLinks";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PaginationLinks;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PaginationLinks;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PaginationLinks;

  static equals(a: PaginationLinks | PlainMessage<PaginationLinks> | undefined, b: PaginationLinks | PlainMessage<PaginationLinks> | undefined): boolean;
}

/**
 * A container for various pagination properties
 *
 * @generated from message dictybase.api.jsonapi.Pagination
 */
export declare class Pagination extends Message<Pagination> {
  /**
   * Total number of entries, regardless of pages.
   *
   * @generated from field: int64 records = 1;
   */
  records: bigint;

  /**
   * Total number of pages.
   *
   * @generated from field: int64 total = 2;
   */
  total: bigint;

  /**
   * Number of entries per page.
   *
   * @generated from field: int64 size = 3;
   */
  size: bigint;

  /**
   * Current page number.
   *
   * @generated from field: int64 number = 4;
   */
  number: bigint;

  constructor(data?: PartialMessage<Pagination>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "dictybase.api.jsonapi.Pagination";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Pagination;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Pagination;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Pagination;

  static equals(a: Pagination | PlainMessage<Pagination> | undefined, b: Pagination | PlainMessage<Pagination> | undefined): boolean;
}

/**
 * Top level meta container.
 *
 * @generated from message dictybase.api.jsonapi.Meta
 */
export declare class Meta extends Message<Meta> {
  /**
   * @generated from field: dictybase.api.jsonapi.Pagination pagination = 1;
   */
  pagination?: Pagination;

  constructor(data?: PartialMessage<Meta>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "dictybase.api.jsonapi.Meta";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Meta;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Meta;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Meta;

  static equals(a: Meta | PlainMessage<Meta> | undefined, b: Meta | PlainMessage<Meta> | undefined): boolean;
}

