// @generated by protoc-gen-es v1.6.0
// @generated from file dictybase/api/jsonapi/payload.proto (package dictybase.api.jsonapi, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * A [resource identifier object](http://jsonapi.org/format/#document-resource-identifier-objects).
 *
 * @generated from message dictybase.api.jsonapi.Data
 */
export const Data = proto3.makeMessageType(
  "dictybase.api.jsonapi.Data",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * Definition for resource identifier collection objects.
 *
 * @generated from message dictybase.api.jsonapi.DataCollection
 */
export const DataCollection = proto3.makeMessageType(
  "dictybase.api.jsonapi.DataCollection",
  () => [
    { no: 2, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 1, name: "data", kind: "message", T: Data, repeated: true },
  ],
);

/**
 * A container for http links.
 *
 * @generated from message dictybase.api.jsonapi.Links
 */
export const Links = proto3.makeMessageType(
  "dictybase.api.jsonapi.Links",
  () => [
    { no: 1, name: "self", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "related", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * A container for pagination links.
 *
 * @generated from message dictybase.api.jsonapi.PaginationLinks
 */
export const PaginationLinks = proto3.makeMessageType(
  "dictybase.api.jsonapi.PaginationLinks",
  () => [
    { no: 1, name: "self", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "next", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "prev", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "last", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "first", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * A container for various pagination properties
 *
 * @generated from message dictybase.api.jsonapi.Pagination
 */
export const Pagination = proto3.makeMessageType(
  "dictybase.api.jsonapi.Pagination",
  () => [
    { no: 1, name: "records", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "total", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "size", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "number", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * Top level meta container.
 *
 * @generated from message dictybase.api.jsonapi.Meta
 */
export const Meta = proto3.makeMessageType(
  "dictybase.api.jsonapi.Meta",
  () => [
    { no: 1, name: "pagination", kind: "message", T: Pagination },
  ],
);

