// @generated by protoc-gen-es v1.6.0
// @generated from file dictybase/api/upload/file.proto (package dictybase.api.upload, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * FileUploadRequest defines requests parameters for uploading
 * a file through protocol buffer. The file is expected to be uploaded
 * grpc client side streaming
 *
 * @generated from message dictybase.api.upload.FileUploadRequest
 */
export const FileUploadRequest = proto3.makeMessageType(
  "dictybase.api.upload.FileUploadRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * FileUploadResponse defines response received after completion of
 * file upload
 *
 * @generated from message dictybase.api.upload.FileUploadResponse
 */
export const FileUploadResponse = proto3.makeMessageType(
  "dictybase.api.upload.FileUploadResponse",
  () => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(FileUploadResponse_Status) },
    { no: 2, name: "msg", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from enum dictybase.api.upload.FileUploadResponse.Status
 */
export const FileUploadResponse_Status = proto3.makeEnum(
  "dictybase.api.upload.FileUploadResponse.Status",
  [
    {no: 0, name: "CREATED"},
    {no: 1, name: "UPDATED"},
  ],
);

