// @generated by protoc-gen-es v1.6.0
// @generated from file dictybase/content/content.proto (package dictybase.content, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FieldMask, proto3, Timestamp } from "@bufbuild/protobuf";
import { Links } from "../api/jsonapi/payload_pb.js";

/**
 * @generated from message dictybase.content.Content
 */
export const Content = proto3.makeMessageType(
  "dictybase.content.Content",
  () => [
    { no: 1, name: "data", kind: "message", T: ContentData },
    { no: 2, name: "links", kind: "message", T: Links },
  ],
);

/**
 * @generated from message dictybase.content.ContentData
 */
export const ContentData = proto3.makeMessageType(
  "dictybase.content.ContentData",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "attributes", kind: "message", T: ContentAttributes },
    { no: 4, name: "links", kind: "message", T: Links },
  ],
);

/**
 * Definition of various content fields
 *
 * @generated from message dictybase.content.ContentAttributes
 */
export const ContentAttributes = proto3.makeMessageType(
  "dictybase.content.ContentAttributes",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "updated_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
    { no: 6, name: "updated_at", kind: "message", T: Timestamp },
    { no: 7, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message dictybase.content.ContentRequest
 */
export const ContentRequest = proto3.makeMessageType(
  "dictybase.content.ContentRequest",
  () => [
    { no: 1, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message dictybase.content.ContentIdRequest
 */
export const ContentIdRequest = proto3.makeMessageType(
  "dictybase.content.ContentIdRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * Definition for fields that are needed for storing the content
 *
 * @generated from message dictybase.content.NewContentAttributes
 */
export const NewContentAttributes = proto3.makeMessageType(
  "dictybase.content.NewContentAttributes",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "created_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "slug", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Definition for storing new content
 *
 * @generated from message dictybase.content.StoreContentRequest
 */
export const StoreContentRequest = proto3.makeMessageType(
  "dictybase.content.StoreContentRequest",
  () => [
    { no: 1, name: "data", kind: "message", T: StoreContentRequest_Data },
  ],
);

/**
 * @generated from message dictybase.content.StoreContentRequest.Data
 */
export const StoreContentRequest_Data = proto3.makeMessageType(
  "dictybase.content.StoreContentRequest.Data",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "attributes", kind: "message", T: NewContentAttributes },
  ],
  {localName: "StoreContentRequest_Data"},
);

/**
 * Fields that can be updated
 * Changing either or both of name and namespace
 * attributes alter the slug for the page
 *
 * @generated from message dictybase.content.ExistingContentAttributes
 */
export const ExistingContentAttributes = proto3.makeMessageType(
  "dictybase.content.ExistingContentAttributes",
  () => [
    { no: 1, name: "updated_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message dictybase.content.UpdateContentRequest
 */
export const UpdateContentRequest = proto3.makeMessageType(
  "dictybase.content.UpdateContentRequest",
  () => [
    { no: 1, name: "data", kind: "message", T: UpdateContentRequest_Data },
    { no: 2, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "update_mask", kind: "message", T: FieldMask },
  ],
);

/**
 * @generated from message dictybase.content.UpdateContentRequest.Data
 */
export const UpdateContentRequest_Data = proto3.makeMessageType(
  "dictybase.content.UpdateContentRequest.Data",
  () => [
    { no: 1, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "attributes", kind: "message", T: ExistingContentAttributes },
  ],
  {localName: "UpdateContentRequest_Data"},
);

