// @generated by protoc-gen-connect-es v1.3.0
// @generated from file dictybase/content/content.proto (package dictybase.content, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Content, ContentIdRequest, ContentRequest, StoreContentRequest, UpdateContentRequest } from "./content_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";
import { HealthzIdRequest } from "../api/jsonapi/request_pb.js";

/**
 * The content service definition
 *
 * @generated from service dictybase.content.ContentService
 */
export declare const ContentService: {
  readonly typeName: "dictybase.content.ContentService",
  readonly methods: {
    /**
     * Gets the content of specified page(slug)
     *
     * @generated from rpc dictybase.content.ContentService.GetContentBySlug
     */
    readonly getContentBySlug: {
      readonly name: "GetContentBySlug",
      readonly I: typeof ContentRequest,
      readonly O: typeof Content,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc dictybase.content.ContentService.GetContent
     */
    readonly getContent: {
      readonly name: "GetContent",
      readonly I: typeof ContentIdRequest,
      readonly O: typeof Content,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Store the content of a new page(slug)
     *
     * @generated from rpc dictybase.content.ContentService.StoreContent
     */
    readonly storeContent: {
      readonly name: "StoreContent",
      readonly I: typeof StoreContentRequest,
      readonly O: typeof Content,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Update the content of an existing page
     *
     * @generated from rpc dictybase.content.ContentService.UpdateContent
     */
    readonly updateContent: {
      readonly name: "UpdateContent",
      readonly I: typeof UpdateContentRequest,
      readonly O: typeof Content,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Delete an existing page along with its content
     *
     * @generated from rpc dictybase.content.ContentService.DeleteContent
     */
    readonly deleteContent: {
      readonly name: "DeleteContent",
      readonly I: typeof ContentIdRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Basic health check that always return success
     *
     * @generated from rpc dictybase.content.ContentService.Healthz
     */
    readonly healthz: {
      readonly name: "Healthz",
      readonly I: typeof HealthzIdRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

